spring.application.name=hotelbookapp

# Cloudinary signed upload
cloudinary.cloud_name=dejzz0spj
cloudinary.api_key=836234674562628
cloudinary.api_secret=IZfLCwv-eaOk6yhrtIf_bMpviu4

# Optional folder for uploads
cloudinary.folder=hotel_images

# Use unsigned upload? true/false
cloudinary.use_unsigned=false
cloudinary.unsigned_preset=hotelapp_unsigned_preset

spring.datasource.url=jdbc:mysql://localhost:3306/hotelbookapp
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=hotelappJwtSecretKeyForAuthenticationSystem2026SecureKey
jwt.expiration=86400000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

razorpay.key.id=rzp_test_SP6YnALebZmwaG
razorpay.key.secret=PpdRc1OV8D67QtEBIAsOuX9Q

server.port=${PORT:8080}